name: OPM Maker

on: 
  push:
    paths:
      - "Custom/*.sopm"
      - ".github/workflows/*.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build OPM
      run: docker run --rm -v ${{ github.workspace }}:/pkg -w /pkg ligero/otrs-itsm otrs.Console.pl Dev::Package::Build --allow-root --module-directory=/pkg Custom/*.sopm /pkg
      

    # Test
    #- name: OPM tests
    #  uses:
    #  run: docker-compose --file scripts/test/docker-compose.test.yml

    - name: Get version tag
      id: get_version
      run: echo ::set-output name=VERSION::$(grep '<Version>' Custom/*.sopm | sed -r 's/.+>(.+)<.+/\1/')

    - uses: rlespinasse/github-slug-action@1.1.1
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_HEAD_REF_SLUG }}
        echo ${{ env.GITHUB_BASE_REF_SLUG }}
      
    - name: Upload OPM
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GITHUB_REF_SLUG }}
        prerelease: false
        title: ${{ steps.get_version.outputs.VERSION }}
        files: |
          *.opm
